### ISSUE TITLE
Specified taxanomy name not in NCBI taxanomy database.

### ISSUE THREAD

**Issue by lijunyuan** [Prunoideae/MitoFlex#11]
Dears,
I installed the [MitoFlex] following your instruction with all needed modules in the conda built environment, and updated the NCBI taxanomy database using ./ncbi.py, finally the .etetoolkit directory was created at my home. I tried the ./MitoFlex.py load-modules, and the result showed that all the modules were OK:
[18:30:05 INFO ] (MitoFlex -> pre@411) : MitoFlex 0.2.9, run 1
[18:30:05 INFO ] (MitoFlex -> pre@414) : Arguments after parsed : 
[18:30:05 INFO ] (MitoFlex -> pre@415) : ['__calling=load-modules']
[18:30:05 INFO ] (MitoFlex -> load_modules@382) : Loading filter module.
[18:30:05 INFO ] (MitoFlex -> load_modules@384) : Loading assemble module.
[18:30:06 INFO ] (MitoFlex -> load_modules@386) : Loading findmitoscaf module.
[18:30:35 INFO ] (MitoFlex -> load_modules@388) : Loading annotation module.
[18:30:35 INFO ] (MitoFlex -> load_modules@390) : Loading visualize module.
[18:30:35 INFO ] (MitoFlex -> load_modules@395) : All modules are loaded correctly.
[18:30:35 INFO ] (MitoFlex -> post@477) : All done! Time elapsed : 30.42s.

However, when I tried ../MitoFlex.py --config test_config.py, an error occurred showing that:
Specified taxanomy name not in NCBI taxanomy database.
Error occured, exiting.

Would you please help to see what is the problem, thanks !

Lijunyuan

**Comment by Prunoideae** [comment]
Looks like your taxonomy database is still not correctly set up. This error occurs when a name not existed in taxonomy database was given to MitoFlex as taxonomy filter. In the test case it should be `Arthropoda`, which should exist in the taxonomy database if it's setup correctly.

Can you try to execute these lines in the python environment you will run MitoFlex in:
```python
from ete3 import NCBITaxa
ncbi = NCBITaxa()
result = ncbi.get_name_translator(["Arthropoda"])
print(result)
```

If your setup is correct, it should output:
```
>>> from ete3 import NCBITaxa
>>> ncbi = NCBITaxa()
>>> result = ncbi.get_name_translator(["Arthropoda"])
>>> print(result)
{'Arthropoda': [6656]}
>>>
```

**Comment by lijunyuan** [comment]
Thanks for your promptly reply, and I have tried as you suggested, but it returned empty like this:
(MitoFlex) which python3
~/anaconda3/envs/MitoFlex/bin/python3
(MitoFlex) python3
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ete3 import NCBITaxa
>>> ncbi = NCBITaxa()
>>> result = ncbi.get_name_translator(["Arthropoda"])
>>> print(result)
{}

**Comment by Prunoideae** [comment]
This is weird, so the NCBI taxonomy database is not set up yet, what's the output of the `ncbi.py` when you execute it?

**Comment by lijunyuan** [comment]
For unknown reasons I can run the program this time after I run the ncbi.py again, thanks for your help!
By the way, is there any method for me to check whether the assemblied sequence is a circular or incompletely linear?

**Comment by Prunoideae** [comment]
You can check the `Circos.png` in output folder, if the sequence is circular, it will be shown as a complete ring, otherwise a gap will be drawn between the end and the start.
